#!/bin/bash -l

# Set SCC project
#$ -P lau-bumc

# Specify hard time limit for the job.
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=252:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m a

# Give job a name
#$ -N sRNA_Pipeline

# Request 1 core
#$ -pe omp 1

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o pirna_pipeline.qlog

# Ask for scratch space
#$ -l scratch=100G

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="

# End of SCC job options ------------------------------------------------------

# Load seqtk
module load seqtk/1.3

# All files need to be from the same library
# Run for 5-7 files
files=(
  AeAlbo_Ovary_OA
  AeAlbo_Testis_OA
  AeAlbo_Mcarc_OA
  AeAlbo_Larv_OA
  AeAlbo_MaleWhole_CT
  AeAlbo_FemaleWhole_Sugar_CT
  AeAlbo_Larvae_CT
  AeAlbo_Pupae_CT
)

# All files' sequencing depth
  # Order corresponds to $files
seqdepth=(
  48076735
  25895868
  29437769
  10155143
  14927280
  16882404
  17940219
  18197857
)

# All files should be from same Species
# This variable indicates the folder that it will be put into
Species=AeAlbo

for index in ${!files[*]}; do 
  this_file=/projectnb/lau-bumc/BFstudents/data/fastq/${files[$index]}.fastq
  this_seq=$(grep "+" $this_file | wc -l)
  #this_seq=${seqdepth[$index]}
  # Loop through percentages
  for perc in 80 60 40 20; do
  reads=$((this_seq*perc/100))
  # Random seed: 10
  seqtk sample -s10 $this_file $reads > /projectnb/lau-bumc/BFstudents/data/Downsampling/$Species/${files[$index]}_$perc.fastq 
  done
done

